from __future__ import annotations

import hashlib
from html import escape

from ..models import ImagePrompt, ParsedIntent, PlaybackManifest, VisualBrief
from ..workflows.state import DrawingWorkflowState
from .base import (
    GeneratedAssetSpec,
    ProviderCapabilities,
    ProviderGateway,
    ProviderProfile,
    ProviderRuntimeInfo,
)


def stable_seed_for_text(input_text: str) -> int:
    digest = hashlib.blake2b(input_text.encode("utf-8"), digest_size=8).digest()
    return int.from_bytes(digest, "big") % 1_000_000


class MockProviderGateway(ProviderGateway):
    @property
    def runtime_info(self) -> ProviderRuntimeInfo:
        return ProviderRuntimeInfo(
            profile=ProviderProfile.mock,
            provider_name="mock-provider",
            placeholder=False,
            network_enabled=False,
            configured=True,
            capabilities=ProviderCapabilities(
                supports_preview=True,
                supports_final=True,
                supports_layer_decomposition=True,
                supports_playback_manifest=True,
            ),
            safe_settings={
                "seedStrategy": "blake2b",
                "assetMode": "file-backed-svg",
                "networkEnabled": False,
            },
        )

    async def parse_intent(self, *, job_id: str, input_text: str, locale: str) -> ParsedIntent:
        return ParsedIntent(
            subject="anime watercolor portrait",
            style="high-quality watercolor illustration",
            composition="half-body portrait with clean character focus",
            constraints=[
                "prioritize polish over speed",
                "preserve readable silhouette",
                "support layer-based playback",
            ],
            edits=[],
            ambiguities=[],
            confidence=0.94,
        )

    async def build_visual_brief(self, state: DrawingWorkflowState) -> VisualBrief:
        return VisualBrief(
            artDirection="soft anime watercolor with polished lighting",
            camera="medium close-up, portrait orientation",
            palette=["sky blue", "rose pink", "warm ivory", "soft violet"],
            mood="dreamy and clean",
            characterSpec=f"Interpret the request as a premium illustrated character portrait based on: {state.inputText}",
            backgroundSpec="minimal watercolor backdrop with soft atmospheric contrast",
            negativeConstraints=["no rough stick-figure canvas output", "no unfinished silhouette"],
        )

    async def build_image_prompt(self, state: DrawingWorkflowState) -> ImagePrompt:
        prompt_seed = stable_seed_for_text(state.inputText)
        return ImagePrompt(
            model="mock-preview-final-pipeline",
            positivePrompt=(
                "Best-quality anime watercolor portrait, refined facial features, layered paint workflow, "
                f"user intent: {state.inputText}"
            ),
            negativePrompt="messy lines, crude canvas doodle, unfinished paint, distorted anatomy",
            size="1024x1024",
            guidance="Preserve the feeling of a staged painting workflow that can later map to playback layers.",
            seed=prompt_seed,
        )

    async def generate_preview(self, state: DrawingWorkflowState) -> GeneratedAssetSpec:
        return GeneratedAssetSpec(
            kind="preview",
            role="preview",
            label="Preview Image",
            mime_type="image/svg+xml",
            width=1024,
            height=1024,
            content_bytes=_build_mock_svg(
                role="preview",
                label="Preview",
                input_text=state.inputText,
                width=1024,
                height=1024,
            ),
            file_extension="svg",
            metadata={
                "provider": "mock-provider",
                "note": "Preview content is a local SVG generated by the mock provider.",
                "inputText": state.inputText,
            },
        )

    async def generate_final_image(self, state: DrawingWorkflowState) -> GeneratedAssetSpec:
        return GeneratedAssetSpec(
            kind="final",
            role="final_image",
            label="Final Image",
            mime_type="image/svg+xml",
            width=1024,
            height=1024,
            content_bytes=_build_mock_svg(
                role="final_image",
                label="Final",
                input_text=state.inputText,
                width=1024,
                height=1024,
            ),
            file_extension="svg",
            metadata={
                "provider": "mock-provider",
                "note": "Final image content is a local SVG generated by the mock provider.",
                "inputText": state.inputText,
            },
        )

    async def decompose_layers(self, state: DrawingWorkflowState) -> list[GeneratedAssetSpec]:
        roles = [
            ("sketch", "Sketch Layer"),
            ("lineart", "Line Art Layer"),
            ("flat_color", "Flat Color Layer"),
            ("shadow", "Shadow Layer"),
            ("lighting", "Lighting Layer"),
            ("details", "Details Layer"),
            ("final_composite", "Final Composite Layer"),
        ]
        return [
            GeneratedAssetSpec(
                kind="layer",
                role=role,
                label=label,
                mime_type="image/svg+xml",
                width=1024,
                height=1024,
                content_bytes=_build_mock_svg(
                    role=role,
                    label=label,
                    input_text=state.inputText,
                    width=1024,
                    height=1024,
                ),
                file_extension="svg",
                metadata={
                    "provider": "mock-provider",
                    "note": f"{label} content is a local SVG generated by the mock provider.",
                },
            )
            for role, label in roles
        ]

    async def build_playback_manifest(self, state: DrawingWorkflowState) -> PlaybackManifest:
        layer_refs = [layer.assetId for layer in state.layerAssets]
        layer_by_role = {layer.role: layer for layer in state.layerAssets}
        return PlaybackManifest(
            manifestVersion="0.1.0",
            canvasSize={"width": 1024, "height": 1024},
            durationMs=6200,
            layerRefs=layer_refs,
            finalCompositeAssetId=state.finalAsset.assetId if state.finalAsset else None,
            steps=[
                _playback_step(step=1, phase="sketch", duration_ms=900, asset=layer_by_role.get("sketch")),
                _playback_step(step=2, phase="lineart", duration_ms=850, asset=layer_by_role.get("lineart")),
                _playback_step(step=3, phase="flat_color", duration_ms=1000, asset=layer_by_role.get("flat_color")),
                _playback_step(step=4, phase="shadow", duration_ms=850, asset=layer_by_role.get("shadow")),
                _playback_step(step=5, phase="lighting", duration_ms=800, asset=layer_by_role.get("lighting")),
                _playback_step(step=6, phase="details", duration_ms=950, asset=layer_by_role.get("details")),
                _playback_step(step=7, phase="final_composite", duration_ms=850, asset=layer_by_role.get("final_composite")),
            ],
        )


def _playback_step(*, step: int, phase: str, duration_ms: int, asset) -> dict:
    payload = {
        "step": step,
        "phase": phase,
        "assetRole": phase,
        "durationMs": duration_ms,
    }
    if asset is not None:
        payload["assetId"] = asset.assetId
        payload["contentUrl"] = asset.contentUrl
    return payload


def _build_mock_svg(*, role: str, label: str, input_text: str, width: int, height: int) -> bytes:
    theme = _theme_for_role(role)
    safe_label = escape(label)
    safe_role = escape(role.replace("_", " "))
    safe_prompt = escape(input_text[:72])
    seed = stable_seed_for_text(f"{role}:{input_text}")
    accent_x = 180 + (seed % 420)
    accent_y = 220 + ((seed // 7) % 360)
    circle_x = 700 + ((seed // 11) % 140)
    circle_y = 220 + ((seed // 13) % 200)

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="{theme['bg_start']}"/>
      <stop offset="100%" stop-color="{theme['bg_end']}"/>
    </linearGradient>
    <linearGradient id="accent" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="{theme['accent']}"/>
      <stop offset="100%" stop-color="{theme['accent_soft']}"/>
    </linearGradient>
  </defs>
  <rect width="{width}" height="{height}" fill="url(#bg)"/>
  <rect x="72" y="72" width="{width - 144}" height="{height - 144}" rx="40" fill="{theme['panel']}" opacity="0.88"/>
  <circle cx="{circle_x}" cy="{circle_y}" r="148" fill="{theme['glow']}" opacity="0.36"/>
  <circle cx="{accent_x}" cy="{accent_y}" r="116" fill="{theme['accent_soft']}" opacity="0.30"/>
  <path d="M180 740 C280 520, 450 470, 560 620 S760 830, 850 650" fill="none" stroke="{theme['stroke']}" stroke-width="{theme['stroke_width']}" stroke-linecap="round"/>
  <path d="M230 800 C340 690, 420 650, 540 705 S720 810, 800 760" fill="none" stroke="{theme['stroke_alt']}" stroke-width="{theme['stroke_alt_width']}" stroke-linecap="round" opacity="0.88"/>
  <rect x="116" y="128" width="220" height="40" rx="20" fill="url(#accent)"/>
  <text x="132" y="156" font-family="Arial, Helvetica, sans-serif" font-size="22" fill="{theme['text_muted']}" letter-spacing="0">VocaSketch Mock Asset</text>
  <text x="116" y="248" font-family="Arial, Helvetica, sans-serif" font-size="76" font-weight="700" fill="{theme['text_main']}" letter-spacing="0">{safe_label}</text>
  <text x="116" y="304" font-family="Arial, Helvetica, sans-serif" font-size="28" fill="{theme['text_muted']}" letter-spacing="0">{safe_role}</text>
  <text x="116" y="890" font-family="Arial, Helvetica, sans-serif" font-size="30" fill="{theme['text_main']}" letter-spacing="0">{safe_prompt}</text>
  <text x="116" y="936" font-family="Arial, Helvetica, sans-serif" font-size="18" fill="{theme['text_muted']}" letter-spacing="0">seed {seed} | local svg placeholder | offline only</text>
</svg>"""
    return svg.encode("utf-8")


def _theme_for_role(role: str) -> dict[str, str]:
    themes = {
        "preview": {
            "bg_start": "#dbeafe",
            "bg_end": "#fce7f3",
            "panel": "#ffffff",
            "accent": "#60a5fa",
            "accent_soft": "#f472b6",
            "glow": "#93c5fd",
            "stroke": "#3b82f6",
            "stroke_alt": "#f472b6",
            "stroke_width": "16",
            "stroke_alt_width": "10",
            "text_main": "#111827",
            "text_muted": "#475569",
        },
        "final_image": {
            "bg_start": "#0f172a",
            "bg_end": "#312e81",
            "panel": "#111827",
            "accent": "#f59e0b",
            "accent_soft": "#38bdf8",
            "glow": "#818cf8",
            "stroke": "#f8fafc",
            "stroke_alt": "#f59e0b",
            "stroke_width": "18",
            "stroke_alt_width": "12",
            "text_main": "#f8fafc",
            "text_muted": "#cbd5e1",
        },
        "sketch": {
            "bg_start": "#f8fafc",
            "bg_end": "#e2e8f0",
            "panel": "#ffffff",
            "accent": "#94a3b8",
            "accent_soft": "#cbd5e1",
            "glow": "#e2e8f0",
            "stroke": "#334155",
            "stroke_alt": "#64748b",
            "stroke_width": "10",
            "stroke_alt_width": "6",
            "text_main": "#0f172a",
            "text_muted": "#475569",
        },
        "lineart": {
            "bg_start": "#ffffff",
            "bg_end": "#f1f5f9",
            "panel": "#ffffff",
            "accent": "#0f172a",
            "accent_soft": "#64748b",
            "glow": "#cbd5e1",
            "stroke": "#020617",
            "stroke_alt": "#334155",
            "stroke_width": "8",
            "stroke_alt_width": "4",
            "text_main": "#020617",
            "text_muted": "#475569",
        },
        "flat_color": {
            "bg_start": "#fef3c7",
            "bg_end": "#fde68a",
            "panel": "#fff7ed",
            "accent": "#fb7185",
            "accent_soft": "#60a5fa",
            "glow": "#fdba74",
            "stroke": "#f97316",
            "stroke_alt": "#ec4899",
            "stroke_width": "18",
            "stroke_alt_width": "14",
            "text_main": "#7c2d12",
            "text_muted": "#9a3412",
        },
        "shadow": {
            "bg_start": "#1e293b",
            "bg_end": "#334155",
            "panel": "#0f172a",
            "accent": "#64748b",
            "accent_soft": "#94a3b8",
            "glow": "#475569",
            "stroke": "#cbd5e1",
            "stroke_alt": "#94a3b8",
            "stroke_width": "16",
            "stroke_alt_width": "10",
            "text_main": "#f8fafc",
            "text_muted": "#cbd5e1",
        },
        "lighting": {
            "bg_start": "#fff7ed",
            "bg_end": "#fef3c7",
            "panel": "#fffbeb",
            "accent": "#f59e0b",
            "accent_soft": "#fde68a",
            "glow": "#fcd34d",
            "stroke": "#f59e0b",
            "stroke_alt": "#fb7185",
            "stroke_width": "20",
            "stroke_alt_width": "12",
            "text_main": "#78350f",
            "text_muted": "#92400e",
        },
        "details": {
            "bg_start": "#ede9fe",
            "bg_end": "#dbeafe",
            "panel": "#f8fafc",
            "accent": "#8b5cf6",
            "accent_soft": "#38bdf8",
            "glow": "#c4b5fd",
            "stroke": "#7c3aed",
            "stroke_alt": "#0ea5e9",
            "stroke_width": "12",
            "stroke_alt_width": "8",
            "text_main": "#1e1b4b",
            "text_muted": "#4338ca",
        },
        "final_composite": {
            "bg_start": "#111827",
            "bg_end": "#1d4ed8",
            "panel": "#111827",
            "accent": "#22c55e",
            "accent_soft": "#38bdf8",
            "glow": "#60a5fa",
            "stroke": "#f8fafc",
            "stroke_alt": "#22c55e",
            "stroke_width": "18",
            "stroke_alt_width": "12",
            "text_main": "#f8fafc",
            "text_muted": "#dbeafe",
        },
    }
    return themes.get(role, themes["preview"])
